### ISSUE TITLE
getting warning when using action to upload image as an artifact.

### ISSUE THREAD

**Issue by kbhavik** [ishworkh/container-image-artifact-upload#8]
![image](https://github.com/user-attachments/assets/4dfdacdd-8386-4388-b6ff-c1a1b1e29d94)

[Deprecation notice: v1, v2, and v3 of the artifact actions](https://github.com/amplify-health/ste-demo-app/actions/runs/10071701252/workflow)
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "action_image_artifact_xxxxxxxxxx_quarantine_webgoat_v1.0.0".
Please update your workflow to use v4 of the artifact actions.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

**Comment by ishworkh** [comment]
Thanks for creating the issue.
I have now released `ishworkh/container-image-artifact-upload@v2.0.0` and `ishworkh/container-image-artifact-download@v2.0.0` with the fixes. Please go ahead and use them, and let me know how it goes :)

**Comment by kbhavik** [comment]
It works fine now and no more warnings. Thanks for the fix.
